# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180813_1251'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile'),
            preserve_default=False,
        ),
    ]
