# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180705_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/static/images/'),
        ),
    ]
