# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20180705_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='Аватар'),
        ),
    ]
