# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20180709_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_short',
        ),
        migrations.AddField(
            model_name='post',
            name='text_full',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
