# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20180710_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_full',
            field=models.TextField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_short',
            field=models.TextField(verbose_name='Короткий текст'),
        ),
    ]
