# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumsubblock_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumblock',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
