# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumblock',
            name='small',
            field=models.CharField(default=1, max_length=200, verbose_name='Мелкий текст'),
            preserve_default=False,
        ),
    ]
