# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_forumblock_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsubblock',
            name='about',
            field=models.CharField(default=1, max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
