# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_forumsubblock_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='views',
            field=models.ManyToManyField(related_name='_forumpost_views_+', to='forum.ForumPost', verbose_name='list of views'),
        ),
    ]
