# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20181209_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='views',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=100000), size=100000),
        ),
    ]
