# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20181209_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='views',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
