# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20181209_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='view',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=1, size=None),
            preserve_default=False,
        ),
    ]
