# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20181209_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='view',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='views',
            field=models.TextField(default=';', verbose_name='list of views'),
            preserve_default=False,
        ),
    ]
