# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_forumblock_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'permissions': (('delete.your', 'delete your post'), ('change.your', 'change text on your post'), ('add.your', 'add your post'), ('delete.foreign', 'delete foreign post'), ('change.foreign', 'change foreign post'), ('close', 'close post'))},
        ),
    ]
