# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20190118_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'permissions': (('post.delete.your', 'delete your post'), ('post.change.your', 'change text on your post'), ('post.add.your', 'add your post'), ('post.delete.foreign', 'delete foreign post'), ('post.change.foreign', 'change foreign post'), ('post.close', 'close post'))},
        ),
    ]
