# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20190119_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'permissions': (('forum.post.add.your', 'add your post'), ('forum.post.delete.foreign', 'delete foreign post'), ('forum.post.change.foreign', 'change foreign post'), ('forum.post.close', 'close post'))},
        ),
    ]
