# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_auto_20190119_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
