# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_auto_20190119_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
