# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180812_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/Без_названия.jpg', upload_to='avatar/'),
        ),
    ]
