# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180705_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/users/PaperTest.jpg', null=True, upload_to='images/users/', verbose_name='Аватар'),
        ),
    ]
