# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180813_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/Zapadno-sibirskaya-layka-na-gazone-lodozo.com_-600x476.png', upload_to='avatars/'),
        ),
    ]
