# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20181123_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
