# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20181123_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rep_minus',
            field=models.TextField(default=' ', verbose_name='list of rep_minus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='rep_plus',
            field=models.TextField(default=' ', verbose_name='list of rep_plus'),
            preserve_default=False,
        ),
    ]
