# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190118_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('profile.ban', 'ban this user'), ('profile.change.your', 'change your profile'), ('profile.rep', 'rep user'))},
        ),
    ]
