# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20190119_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('profile.ban', 'ban this user'), ('profile.rep', 'rep user'))},
        ),
    ]
